name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sudo apt-get install -y groff pdftk pdfgrep
      - name: Build the PDF
        run: make
      - name: Release PDF
        uses: akkuman/gitea-release-action@v1
        with:
          files: |-
            demo.pdf
